apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "aksgourav"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "aksgourav"
    spec:
      containers:
        - name: "aksgourav"
          image: "acrgourav.azurecr.io/aksgourav"
          ports:
          - containerPort: 8080
